version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es2
      - cluster.initial_master_nodes=es1,es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es2
    environment:
      - node.name=es2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es1
      - cluster.initial_master_nodes=es1,es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_2:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  pg_data:
    driver: local
  es_data_1:
    driver: local
  es_data_2:
    driver: local

networks:
  elastic:
    driver: bridge